/** WorkforceCtrl — projects, workers, attendance, expenses, advances, payouts. */
export {};
const df = require((global as any).appRoot + '/utils/dflower.utils');
const cntxtDtls = df.getModuleMetaData(__dirname, __filename);
const Mdl = require('../models/WorkforceMdl');

const ok  = (req: any, res: any, fnm: string, data: any, opts: any = {}) => df.formatSucessRes(req, res, data, cntxtDtls, fnm, opts);
const err = (res: any, fnm: string, e: any, status = 500) => df.formatErrorRes(res, null, cntxtDtls, fnm, { error_status: status, err_message: e.message || e });

// ── Ownership guards (IDOR defence) ──
// Every id-based handler must confirm the caller owns the target project (directly, or
// via the worker / contractor / bill / incident that hangs off it) BEFORE reading or
// mutating anything. `guard` runs the check, and on failure emits a 403 and returns
// false — the handler must then `return`. Without this any builder could read/mutate
// another builder's workers, attendance, payroll, bills, compliance and worker PII.
const own = {
  project:    (req: any, id: number) => Mdl.assertProjectOwnerMdl(req.user.id, id, req),
  worker:     (req: any, id: number) => Mdl.assertWorkerOwnerMdl(req.user.id, id, req),
  contractor: (req: any, id: number) => Mdl.assertContractorOwnerMdl(req.user.id, id, req),
  bill:       (req: any, id: number) => Mdl.assertBillOwnerMdl(req.user.id, id, req),
  incident:   (req: any, id: number) => Mdl.assertIncidentOwnerMdl(req.user.id, id, req),
};
const guard = async (res: any, fnm: string, check: Promise<any[]>): Promise<boolean> => {
  const r = await check;
  if (r && r.length) return true;
  df.formatErrorRes(res, null, cntxtDtls, fnm, { error_status: 403, err_message: 'Forbidden' });
  return false;
};

// Projects
exports.listProjectsCtrl = async (req: any, res: any) => { const fnm='listProjectsCtrl'; try { return ok(req,res,fnm, await Mdl.listProjectsMdl(req.user.id, req)); } catch(e:any){ return err(res,fnm,e);} };
exports.createProjectCtrl = async (req: any, res: any) => { const fnm='createProjectCtrl'; const d=req.body.data||req.body; if(!d.name) return err(res,fnm,'name is required',400); try { const o=await Mdl.createProjectMdl(req.user.id,d,req); return ok(req,res,fnm,o[0],{success_status:201,success_msg:'Project created'}); } catch(e:any){ return err(res,fnm,e);} };
exports.updateProjectStatusCtrl = async (req: any, res: any) => { const fnm='updateProjectStatusCtrl'; const d=req.body.data||req.body; const status=d.status; if(!['not_started','in_progress','completed'].includes(status)) return err(res,fnm,'invalid status',400); try { const o=await Mdl.updateProjectStatusMdl(req.user.id, Number(req.params.projectId), status, req); if(!o[0]) return err(res,fnm,'project not found',404); return ok(req,res,fnm,o[0],{success_msg:'Status updated'}); } catch(e:any){ return err(res,fnm,e);} };

// Supervisors
exports.listSupervisorsCtrl = async (req: any, res: any) => { const fnm='listSupervisorsCtrl'; const pid=Number(req.params.projectId); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; return ok(req,res,fnm, await Mdl.listSupervisorsMdl(pid, req)); } catch(e:any){ return err(res,fnm,e);} };
exports.addSupervisorCtrl = async (req: any, res: any) => { const fnm='addSupervisorCtrl'; const d=req.body.data||req.body; const pid=Number(req.params.projectId); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; const o=await Mdl.addSupervisorMdl(pid,d,req); return ok(req,res,fnm,o[0],{success_status:201,success_msg:'Supervisor added'}); } catch(e:any){ return err(res,fnm,e);} };

// Workers
exports.listWorkersCtrl = async (req: any, res: any) => { const fnm='listWorkersCtrl'; const pid=Number(req.params.projectId); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; return ok(req,res,fnm, await Mdl.listWorkersMdl(pid, req)); } catch(e:any){ return err(res,fnm,e);} };
exports.addWorkerCtrl = async (req: any, res: any) => { const fnm='addWorkerCtrl'; const d=req.body.data||req.body; const pid=Number(req.params.projectId); if(!d.name) return err(res,fnm,'name is required',400); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; const o=await Mdl.addWorkerMdl(pid,d,req); return ok(req,res,fnm,o[0],{success_status:201,success_msg:'Worker added'}); } catch(e:any){ return err(res,fnm,e);} };

// Ghost-worker / duplicate check — call before enrolling to catch a person already on
// the books (same Aadhaar or mobile) somewhere in this owner's projects.
exports.checkDuplicateWorkerCtrl = async (req: any, res: any) => { const fnm='checkDuplicateWorkerCtrl'; const aadhaar=(req.query.aadhaar||'').toString().trim()||null; const mobile=(req.query.mobile||'').toString().trim()||null; if(!aadhaar&&!mobile) return err(res,fnm,'aadhaar or mobile is required',400); try { const matches=await Mdl.checkDuplicateWorkerMdl(req.user.id, aadhaar, mobile, req); return ok(req,res,fnm,{ duplicate: matches.length>0, matches }); } catch(e:any){ return err(res,fnm,e);} };

// Attendance
exports.getAttendanceCtrl = async (req: any, res: any) => { const fnm='getAttendanceCtrl'; const pid=Number(req.params.projectId); const from=req.query.from||new Date().toISOString().slice(0,10); const to=req.query.to||from; try { if(!(await guard(res,fnm,own.project(req,pid)))) return; return ok(req,res,fnm, await Mdl.getAttendanceMdl(pid, from, to, req)); } catch(e:any){ return err(res,fnm,e);} };
exports.markAttendanceCtrl = async (req: any, res: any) => { const fnm='markAttendanceCtrl'; const d=req.body.data||req.body; const pid=Number(req.params.projectId); if(!d.workerId||!d.date) return err(res,fnm,'workerId and date are required',400); d.markedBy=req.user.id; try { if(!(await guard(res,fnm,own.project(req,pid)))) return; const o=await Mdl.markAttendanceMdl(pid,d,req); return ok(req,res,fnm,o[0],{success_msg:'Attendance saved'}); } catch(e:any){ return err(res,fnm,e);} };

// Digital muster roll — statutory-format register for a month: one row per worker with
// their daily P/A/H/L/WO marks, plus day/OT totals and verified-punch counts.
exports.getMusterRollCtrl = async (req: any, res: any) => { const fnm='getMusterRollCtrl'; const pid=Number(req.params.projectId); const month=String(req.query.month||new Date().toISOString().slice(0,7)); if(!/^\d{4}-\d{2}$/.test(month)) return err(res,fnm,'month must be YYYY-MM',400); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; return ok(req,res,fnm, await Mdl.getMusterRollMdl(pid, month, req)); } catch(e:any){ return err(res,fnm,e);} };

// Expenses
exports.listExpensesCtrl = async (req: any, res: any) => { const fnm='listExpensesCtrl'; const pid=Number(req.params.projectId); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; return ok(req,res,fnm, await Mdl.listExpensesMdl(pid, req)); } catch(e:any){ return err(res,fnm,e);} };
exports.addExpenseCtrl = async (req: any, res: any) => { const fnm='addExpenseCtrl'; const d=req.body.data||req.body; const pid=Number(req.params.projectId); if(!d.title||d.amount==null) return err(res,fnm,'title and amount are required',400); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; const o=await Mdl.addExpenseMdl(pid,d,req); return ok(req,res,fnm,o[0],{success_status:201,success_msg:'Expense added'}); } catch(e:any){ return err(res,fnm,e);} };

// Advances
exports.addAdvanceCtrl = async (req: any, res: any) => { const fnm='addAdvanceCtrl'; const d=req.body.data||req.body; const wid=Number(req.params.workerId); if(d.amount==null) return err(res,fnm,'amount is required',400); try { if(!(await guard(res,fnm,own.worker(req,wid)))) return; const o=await Mdl.addAdvanceMdl(wid,d,req); return ok(req,res,fnm,o[0],{success_status:201,success_msg:'Advance recorded'}); } catch(e:any){ return err(res,fnm,e);} };
exports.listAdvancesCtrl = async (req: any, res: any) => { const fnm='listAdvancesCtrl'; const wid=Number(req.params.workerId); try { if(!(await guard(res,fnm,own.worker(req,wid)))) return; return ok(req,res,fnm, await Mdl.listAdvancesMdl(wid, req)); } catch(e:any){ return err(res,fnm,e);} };

// Payouts
exports.addPayoutCtrl = async (req: any, res: any) => { const fnm='addPayoutCtrl'; const d=req.body.data||req.body; const pid=Number(req.params.projectId); if(!d.workerId||d.amount==null) return err(res,fnm,'workerId and amount are required',400); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; const o=await Mdl.addPayoutMdl(pid,d,req); return ok(req,res,fnm,o[0],{success_status:201,success_msg:'Payout recorded'}); } catch(e:any){ return err(res,fnm,e);} };
exports.listPayoutsCtrl = async (req: any, res: any) => { const fnm='listPayoutsCtrl'; const pid=Number(req.params.projectId); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; return ok(req,res,fnm, await Mdl.listPayoutsMdl(pid, req)); } catch(e:any){ return err(res,fnm,e);} };

// Contractors & billing
exports.listContractorsCtrl = async (req: any, res: any) => { const fnm='listContractorsCtrl'; const pid=Number(req.params.projectId); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; return ok(req,res,fnm, await Mdl.listContractorsMdl(pid, req)); } catch(e:any){ return err(res,fnm,e);} };
exports.addContractorCtrl = async (req: any, res: any) => { const fnm='addContractorCtrl'; const d=req.body.data||req.body; const pid=Number(req.params.projectId); if(!d.name) return err(res,fnm,'name is required',400); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; const o=await Mdl.addContractorMdl(pid,d,req); return ok(req,res,fnm,o[0],{success_status:201,success_msg:'Contractor added'}); } catch(e:any){ return err(res,fnm,e);} };
// Preview reconciliation (system truth from the muster) before raising/approving a bill.
exports.reconcileContractorCtrl = async (req: any, res: any) => { const fnm='reconcileContractorCtrl'; const cid=Number(req.params.contractorId); const from=String(req.query.from||''); const to=String(req.query.to||''); if(!from||!to) return err(res,fnm,'from and to are required',400); try { if(!(await guard(res,fnm,own.contractor(req,cid)))) return; const o=await Mdl.reconcileContractorMdl(cid, from, to, req); return ok(req,res,fnm,o[0]||null); } catch(e:any){ return err(res,fnm,e);} };
exports.createContractorBillCtrl = async (req: any, res: any) => { const fnm='createContractorBillCtrl'; const d=req.body.data||req.body; if(!d.contractorId||!d.from||!d.to) return err(res,fnm,'contractorId, from and to are required',400); try { if(!(await guard(res,fnm,own.contractor(req,Number(d.contractorId))))) return; const o=await Mdl.createContractorBillMdl(d,req); return ok(req,res,fnm,o[0],{success_status:201,success_msg:'Bill created'}); } catch(e:any){ return err(res,fnm,e);} };
exports.listContractorBillsCtrl = async (req: any, res: any) => { const fnm='listContractorBillsCtrl'; const pid=Number(req.params.projectId); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; return ok(req,res,fnm, await Mdl.listContractorBillsMdl(pid, req)); } catch(e:any){ return err(res,fnm,e);} };
exports.setContractorBillStatusCtrl = async (req: any, res: any) => { const fnm='setContractorBillStatusCtrl'; const d=req.body.data||req.body; const bid=Number(req.params.billId); if(!['draft','approved','paid','disputed'].includes(d.status)) return err(res,fnm,'invalid status',400); try { if(!(await guard(res,fnm,own.bill(req,bid)))) return; const o=await Mdl.setContractorBillStatusMdl(bid, d.status, req); if(!o[0]) return err(res,fnm,'bill not found',404); return ok(req,res,fnm,o[0],{success_msg:'Bill updated'}); } catch(e:any){ return err(res,fnm,e);} };

// Digital Worker Passport
exports.getWorkerPassportCtrl = async (req: any, res: any) => { const fnm='getWorkerPassportCtrl'; const wid=Number(req.params.workerId); try { if(!(await guard(res,fnm,own.worker(req,wid)))) return; const rows=await Mdl.getWorkerPassportMdl(wid, req); const p=rows[0]; if(!p) return err(res,fnm,'worker not found',404); const certs=await Mdl.listWorkerCertsMdl(wid, req); const marked=Number(p.marked_days)||0; const present=Number(p.present_days)||0; const verified=Number(p.verified_cnt)||0; const flagged=Number(p.flagged_cnt)||0; const reliability=marked?Math.round(present/marked*100):null; const trust=(verified+flagged)?Math.round(verified/(verified+flagged)*100):null; return ok(req,res,fnm,{ profile:{ workerId:p.workr_id, name:p.nm_tx, trade:p.trade_tx, skill:p.skill_cd, photo:p.photo_url_tx, code:p.emp_cd, mobile:p.mobile_tx }, stats:{ projects:Number(p.projects_cnt)||0, builders:Number(p.builders_cnt)||0, firstJoined:p.first_joined_dt, presentDays:present, reliabilityPct:reliability, verifiedPunches:verified, trustPct:trust }, certs }); } catch(e:any){ return err(res,fnm,e);} };
exports.addWorkerCertCtrl = async (req: any, res: any) => { const fnm='addWorkerCertCtrl'; const d=req.body.data||req.body; const wid=Number(req.params.workerId); if(!d.name) return err(res,fnm,'name is required',400); try { if(!(await guard(res,fnm,own.worker(req,wid)))) return; const o=await Mdl.addWorkerCertMdl(wid,d,req); return ok(req,res,fnm,o[0],{success_status:201,success_msg:'Certification added'}); } catch(e:any){ return err(res,fnm,e);} };
exports.listWorkerCertsCtrl = async (req: any, res: any) => { const fnm='listWorkerCertsCtrl'; const wid=Number(req.params.workerId); try { if(!(await guard(res,fnm,own.worker(req,wid)))) return; return ok(req,res,fnm, await Mdl.listWorkerCertsMdl(wid, req)); } catch(e:any){ return err(res,fnm,e);} };

// Statutory compliance run (PF / ESI / BOCW) for a project + month.
exports.getComplianceCtrl = async (req: any, res: any) => { const fnm='getComplianceCtrl'; const pid=Number(req.params.projectId); const month=String(req.query.month||new Date().toISOString().slice(0,7)); if(!/^\d{4}-\d{2}$/.test(month)) return err(res,fnm,'month must be YYYY-MM',400); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; const rows=await Mdl.computeComplianceMdl(pid, month, req); const n=(v:any)=>Number(v)||0; const t=rows.reduce((s:any,r:any)=>({ gross:s.gross+n(r.gross_am), pfEmp:s.pfEmp+n(r.pf_employee_am), pfEr:s.pfEr+n(r.pf_employer_am), esiEmp:s.esiEmp+n(r.esi_employee_am), esiEr:s.esiEr+n(r.esi_employer_am), net:s.net+n(r.net_am) }), { gross:0,pfEmp:0,pfEr:0,esiEmp:0,esiEr:0,net:0 }); const bocwRate=rows[0]?n(rows[0].bocw_rate):1; const bocwCess=Math.round(t.gross*bocwRate/100*100)/100; return ok(req,res,fnm,{ month, rows, totals:{ ...t, bocwRate, bocwCess, pfTotal:Math.round((t.pfEmp+t.pfEr)*100)/100, esiTotal:Math.round((t.esiEmp+t.esiEr)*100)/100 } }); } catch(e:any){ return err(res,fnm,e);} };

// Daily Progress Report + cost tracking
exports.listDprCtrl = async (req: any, res: any) => { const fnm='listDprCtrl'; const pid=Number(req.params.projectId); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; return ok(req,res,fnm, await Mdl.listDprMdl(pid, req)); } catch(e:any){ return err(res,fnm,e);} };
exports.addDprCtrl = async (req: any, res: any) => { const fnm='addDprCtrl'; const d=req.body.data||req.body; const pid=Number(req.params.projectId); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; const o=await Mdl.addDprMdl(pid,d,req.user.id,req); return ok(req,res,fnm,o[0],{success_status:201,success_msg:'DPR saved'}); } catch(e:any){ return err(res,fnm,e);} };
exports.getCostSummaryCtrl = async (req: any, res: any) => { const fnm='getCostSummaryCtrl'; const pid=Number(req.params.projectId); const month=req.query.month?String(req.query.month):null; if(month&&!/^\d{4}-\d{2}$/.test(month)) return err(res,fnm,'month must be YYYY-MM',400); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; const rows=await Mdl.getCostSummaryMdl(pid, month, req); const r=rows[0]||{}; const n=(v:any)=>Number(v)||0; const actual=n(r.labour_am)+n(r.expenses_am); const budget=r.budget_am!=null?n(r.budget_am):null; return ok(req,res,fnm,{ budget, actual, variance: budget!=null?Math.round((budget-actual)*100)/100:null, breakdown:{ labour:n(r.labour_am), material:n(r.material_am), equipment:n(r.equipment_am), transport:n(r.transport_am), misc:n(r.misc_am) } }); } catch(e:any){ return err(res,fnm,e);} };
exports.setProjectBudgetCtrl = async (req: any, res: any) => { const fnm='setProjectBudgetCtrl'; const d=req.body.data||req.body; if(d.budget==null) return err(res,fnm,'budget is required',400); try { const o=await Mdl.setProjectBudgetMdl(req.user.id, Number(req.params.projectId), Number(d.budget), req); if(!o[0]) return err(res,fnm,'project not found',404); return ok(req,res,fnm,o[0],{success_msg:'Budget updated'}); } catch(e:any){ return err(res,fnm,e);} };

// Safety & incidents
exports.listIncidentsCtrl = async (req: any, res: any) => { const fnm='listIncidentsCtrl'; const pid=Number(req.params.projectId); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; return ok(req,res,fnm, await Mdl.listIncidentsMdl(pid, req)); } catch(e:any){ return err(res,fnm,e);} };
exports.addIncidentCtrl = async (req: any, res: any) => { const fnm='addIncidentCtrl'; const d=req.body.data||req.body; const pid=Number(req.params.projectId); if(!d.type||!d.description) return err(res,fnm,'type and description are required',400); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; const o=await Mdl.addIncidentMdl(pid,d,req.user.id,req); return ok(req,res,fnm,o[0],{success_status:201,success_msg:'Incident reported'}); } catch(e:any){ return err(res,fnm,e);} };
exports.setIncidentStatusCtrl = async (req: any, res: any) => { const fnm='setIncidentStatusCtrl'; const d=req.body.data||req.body; const iid=Number(req.params.incidentId); if(!['open','closed'].includes(d.status)) return err(res,fnm,'invalid status',400); try { if(!(await guard(res,fnm,own.incident(req,iid)))) return; const o=await Mdl.setIncidentStatusMdl(iid, d.status, req); if(!o[0]) return err(res,fnm,'incident not found',404); return ok(req,res,fnm,o[0],{success_msg:'Incident updated'}); } catch(e:any){ return err(res,fnm,e);} };
exports.getSafetySummaryCtrl = async (req: any, res: any) => { const fnm='getSafetySummaryCtrl'; const pid=Number(req.params.projectId); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; const rows=await Mdl.getSafetySummaryMdl(pid, req); return ok(req,res,fnm, rows[0]||null); } catch(e:any){ return err(res,fnm,e);} };

// Management dashboard KPIs + "needs attention" inbox (pragmatic approvals surface).
exports.getProjectKpisCtrl = async (req: any, res: any) => { const fnm='getProjectKpisCtrl'; const pid=Number(req.params.projectId); const month=String(req.query.month||new Date().toISOString().slice(0,7)); if(!/^\d{4}-\d{2}$/.test(month)) return err(res,fnm,'month must be YYYY-MM',400); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; const rows=await Mdl.getProjectKpisMdl(pid, month, req); const r=rows[0]||{}; const n=(v:any)=>Number(v)||0; const verified=n(r.verified_cnt); const flagged=n(r.flagged_cnt); const trustPct=(verified+flagged)?Math.round(verified/(verified+flagged)*100):null; const alerts:any[]=[]; if(flagged>0) alerts.push({ kind:'attendance', severity:'high', count:flagged, message:`${flagged} attendance punch(es) flagged outside the site geofence`, go:'muster' }); if(n(r.overclaim_bills)>0) alerts.push({ kind:'billing', severity:'high', count:n(r.overclaim_bills), message:`${n(r.overclaim_bills)} contractor bill(s) over-claim vs the muster`, go:'contractors' }); if(n(r.serious_incidents)>0) alerts.push({ kind:'safety', severity:'critical', count:n(r.serious_incidents), message:`${n(r.serious_incidents)} serious safety incident(s) still open`, go:'safety' }); return ok(req,res,fnm,{ month, kpis:{ workers:n(r.worker_cnt), presentToday:n(r.present_today), monthWage:n(r.month_wage_am), verifiedPunches:verified, flaggedPunches:flagged, trustPct, openIncidents:n(r.open_incidents), budget:r.budget_am!=null?n(r.budget_am):null }, alerts }); } catch(e:any){ return err(res,fnm,e);} };

// AI insights — grounded analytics over the project's real data (fraud, forecast,
// contractor rating, payroll audit). Assembled from several targeted queries.
exports.getAiInsightsCtrl = async (req: any, res: any) => { const fnm='getAiInsightsCtrl'; const prjct=Number(req.params.projectId); const month=String(req.query.month||new Date().toISOString().slice(0,7)); if(!/^\d{4}-\d{2}$/.test(month)) return err(res,fnm,'month must be YYYY-MM',400); try { if(!(await guard(res,fnm,own.project(req,prjct)))) return; const [fraud, dups, forecast, contractors, audit] = await Promise.all([ Mdl.detectAttendanceFraudMdl(prjct, month, req), Mdl.detectDuplicatesInProjectMdl(prjct, req), Mdl.forecastManpowerMdl(prjct, req), Mdl.rateContractorsMdl(prjct, req), Mdl.auditPayrollMdl(prjct, month, req) ]); const n=(v:any)=>Number(v)||0; const rated=(contractors||[]).map((c:any)=>{ const over=n(c.avg_overclaim_pct); const disp=n(c.disputes); const score=Math.max(0, Math.min(100, Math.round(100 - Math.max(0,over)*2 - disp*10))); return { contractorId:c.cntrctr_id, name:c.nm_tx, bills:n(c.bills), avgOverclaimPct:over, disputes:disp, rating:score }; }); const f=forecast[0]||{}; return ok(req,res,fnm,{ month, fraud:{ flaggedWorkers:fraud||[], duplicates:dups||[] }, forecast:{ avgPresent:n(f.avg_present), peakPresent:n(f.peak_present), daysSampled:n(f.days_sampled), suggestedManpower:n(f.avg_present) }, contractors:rated, payrollAudit:audit||[] }); } catch(e:any){ return err(res,fnm,e);} };

// ── Flats / units + sales (035) ──
exports.listUnitsCtrl = async (req: any, res: any) => { const fnm='listUnitsCtrl'; const pid=Number(req.params.projectId); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; return ok(req,res,fnm, await Mdl.listUnitsMdl(pid, req)); } catch(e:any){ return err(res,fnm,e);} };
exports.addUnitCtrl = async (req: any, res: any) => { const fnm='addUnitCtrl'; const d=req.body.data||req.body; const pid=Number(req.params.projectId); if(!d.number) return err(res,fnm,'flat number is required',400); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; const o=await Mdl.addUnitMdl(pid,d,req); return ok(req,res,fnm,o[0],{success_status:201,success_msg:'Flat added'}); } catch(e:any){ return err(res,fnm,e);} };
exports.updateUnitCtrl = async (req: any, res: any) => { const fnm='updateUnitCtrl'; const d=req.body.data||req.body; const uid=Number(req.params.unitId); try { if(!(await guard(res,fnm,Mdl.assertUnitOwnerMdl(req.user.id,uid,req)))) return; const o=await Mdl.updateUnitMdl(uid,d,req); if(!o[0]) return err(res,fnm,'unit not found',404); return ok(req,res,fnm,o[0],{success_msg:'Flat updated'}); } catch(e:any){ return err(res,fnm,e);} };
exports.removeUnitCtrl = async (req: any, res: any) => { const fnm='removeUnitCtrl'; const uid=Number(req.params.unitId); try { if(!(await guard(res,fnm,Mdl.assertUnitOwnerMdl(req.user.id,uid,req)))) return; await Mdl.removeUnitMdl(uid,req); return ok(req,res,fnm,{ removed:true }); } catch(e:any){ return err(res,fnm,e);} };
exports.listUnitDocsCtrl = async (req: any, res: any) => { const fnm='listUnitDocsCtrl'; const uid=Number(req.params.unitId); try { if(!(await guard(res,fnm,Mdl.assertUnitOwnerMdl(req.user.id,uid,req)))) return; return ok(req,res,fnm, await Mdl.listUnitDocsMdl(uid, req)); } catch(e:any){ return err(res,fnm,e);} };
exports.addUnitDocCtrl = async (req: any, res: any) => { const fnm='addUnitDocCtrl'; const d=req.body.data||req.body; const uid=Number(req.params.unitId); if(!d.name) return err(res,fnm,'name is required',400); try { if(!(await guard(res,fnm,Mdl.assertUnitOwnerMdl(req.user.id,uid,req)))) return; const o=await Mdl.addUnitDocMdl(uid,d,req); return ok(req,res,fnm,o[0],{success_status:201,success_msg:'Document added'}); } catch(e:any){ return err(res,fnm,e);} };
exports.removeUnitDocCtrl = async (req: any, res: any) => { const fnm='removeUnitDocCtrl'; const did=Number(req.params.docId); try { if(!(await guard(res,fnm,Mdl.assertUnitDocOwnerMdl(req.user.id,did,req)))) return; await Mdl.removeUnitDocMdl(did,req); return ok(req,res,fnm,{ removed:true }); } catch(e:any){ return err(res,fnm,e);} };
exports.getSalesSummaryCtrl = async (req: any, res: any) => { const fnm='getSalesSummaryCtrl'; const pid=Number(req.params.projectId); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; const o=await Mdl.salesSummaryMdl(pid, req); return ok(req,res,fnm,o[0]); } catch(e:any){ return err(res,fnm,e);} };

// ── Staged project documents ──
exports.listProjectDocsCtrl = async (req: any, res: any) => { const fnm='listProjectDocsCtrl'; const pid=Number(req.params.projectId); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; return ok(req,res,fnm, await Mdl.listProjectDocsMdl(pid, req)); } catch(e:any){ return err(res,fnm,e);} };
exports.addProjectDocCtrl = async (req: any, res: any) => { const fnm='addProjectDocCtrl'; const d=req.body.data||req.body; const pid=Number(req.params.projectId); if(!d.name) return err(res,fnm,'name is required',400); try { if(!(await guard(res,fnm,own.project(req,pid)))) return; const o=await Mdl.addProjectDocMdl(pid,d,req); return ok(req,res,fnm,o[0],{success_status:201,success_msg:'Document added'}); } catch(e:any){ return err(res,fnm,e);} };
exports.removeProjectDocCtrl = async (req: any, res: any) => { const fnm='removeProjectDocCtrl'; const did=Number(req.params.docId); try { if(!(await guard(res,fnm,Mdl.assertProjectDocOwnerMdl(req.user.id,did,req)))) return; await Mdl.removeProjectDocMdl(did,req); return ok(req,res,fnm,{ removed:true }); } catch(e:any){ return err(res,fnm,e);} };

// ── Multi-site: shift a worker to another site ──
exports.moveWorkerCtrl = async (req: any, res: any) => { const fnm='moveWorkerCtrl'; const d=req.body.data||req.body; const wid=Number(req.params.workerId); const toPrjct=Number(d.toProjectId); if(!toPrjct) return err(res,fnm,'toProjectId is required',400); try { if(!(await guard(res,fnm,own.worker(req,wid)))) return; if(!(await guard(res,fnm,own.project(req,toPrjct)))) return; const o=await Mdl.moveWorkerMdl(req.user.id, wid, toPrjct, d.toSupervisorId?Number(d.toSupervisorId):null, req); return ok(req,res,fnm,o[0],{success_msg:'Worker shifted'}); } catch(e:any){ return err(res,fnm,e);} };
exports.listWorkerAssignmentsCtrl = async (req: any, res: any) => { const fnm='listWorkerAssignmentsCtrl'; const wid=Number(req.params.workerId); try { if(!(await guard(res,fnm,own.worker(req,wid)))) return; return ok(req,res,fnm, await Mdl.listWorkerAssignmentsMdl(wid, req)); } catch(e:any){ return err(res,fnm,e);} };
